variable "region" {}
variable "iam_username" {}
variable "state_bucket" {}
variable "table_name" {}
variable "static_domain" {}
variable "dns_ttl" {}
variable "static_bucket" {}
variable "force_destroy" {}
variable "versioning_status" {}
